import 'package:car_part/features/bill/data/local/model/cached_bill.dart';
import 'package:car_part/features/purchase_bill/data/local/model/cached_purchase_bill.dart';
import 'package:drift/drift.dart';
import 'connection/connection.dart' as impl;
// Generated by drift_dev when running `build_runner build`
part 'database.g.dart';

@DriftDatabase(tables: [CachedBill, CachcedPurchaseBill])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(impl.openConnection(logStatements: true));

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      onUpgrade: ((m, from, to) async {
        if (from < 3) {
          m.create(cachcedPurchaseBill);
        }
      }),
      beforeOpen: (details) async {
        // Make sure that foreign keys are enabled
        await customStatement('PRAGMA foreign_keys = ON');
      },
    );
  }
}
